server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flightsearch
    username: huseyin
    password: huseyin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

swagger:
  openapi:
    dev-url: http://localhost:8080

